'use client';

import { Button } from '@/components/ui/button';
import { ExternalLink, FileText, Download } from 'lucide-react';

interface Content {
  id: string;
  title: string;
  type: 'blog' | 'product_description' | 'seo' | 'social' | 'email';
  agent: string;
  createdAt: Date;
  platform: 'notion' | 'google_drive' | 'local';
  link?: string;
  preview: string;
  status: 'draft' | 'published' | 'scheduled';
  wordCount: number;
}

const contents: Content[] = [
  {
    id: '1',
    title: 'Guide Ultime de la Mode Durable 2024',
    type: 'blog',
    agent: 'MARKETING',
    createdAt: new Date(Date.now() - 3600000),
    platform: 'notion',
    link: 'https://notion.so/...',
    preview: 'Un guide complet sur les matières éco-responsables, les marques éthiques et les habitudes d\'achat durables…',
    status: 'published',
    wordCount: 2847,
  },
  {
    id: '2',
    title: 'Descriptions Produits — Collection Été',
    type: 'product_description',
    agent: 'PRODUCT',
    createdAt: new Date(Date.now() - 7200000),
    platform: 'google_drive',
    link: 'https://drive.google.com/...',
    preview: 'Descriptions optimisées SEO pour 45 produits estivaux avec mots-clés et arguments de vente…',
    status: 'draft',
    wordCount: 1234,
  },
  {
    id: '3',
    title: 'Campagne Email — Annonce Soldes de Noël',
    type: 'email',
    agent: 'MARKETING',
    createdAt: new Date(Date.now() - 10800000),
    platform: 'notion',
    link: 'https://notion.so/...',
    preview: 'Texte email engageant pour les soldes avec objets alternatifs et variations de CTA…',
    status: 'scheduled',
    wordCount: 456,
  },
  {
    id: '4',
    title: 'Métas SEO — Produits Phares',
    type: 'seo',
    agent: 'PRODUCT',
    createdAt: new Date(Date.now() - 14400000),
    platform: 'local',
    preview: 'Titres et descriptions méta optimisés pour les 20 meilleurs produits…',
    status: 'published',
    wordCount: 892,
  },
  {
    id: '5',
    title: 'Posts Réseaux Sociaux — Contenu Hebdo',
    type: 'social',
    agent: 'MARKETING',
    createdAt: new Date(Date.now() - 18000000),
    platform: 'google_drive',
    link: 'https://drive.google.com/...',
    preview: '14 posts pour Instagram, Twitter et Facebook avec légendes et hashtags…',
    status: 'draft',
    wordCount: 678,
  },
];

const typeLabels: Record<Content['type'], string> = {
  blog: 'Blog',
  product_description: 'Description',
  seo: 'SEO',
  social: 'Réseaux sociaux',
  email: 'Email',
};

const typeColors: Record<Content['type'], string> = {
  blog:                 'bg-blue-500/10 text-blue-500 border-blue-500/20',
  product_description:  'bg-[var(--armada-primary)]/10 text-[var(--armada-primary)] border-[var(--armada-primary)]/20',
  seo:                  'bg-green-500/10 text-green-600 border-green-500/20',
  social:               'bg-purple-500/10 text-purple-500 border-purple-500/20',
  email:                'bg-yellow-500/10 text-yellow-600 border-yellow-500/20',
};

const statusLabels: Record<Content['status'], string> = {
  published: 'Publié',   // i18n: Published
  draft:     'Brouillon', // i18n: Draft
  scheduled: 'Planifié',  // i18n: Scheduled
};

const statusColors: Record<Content['status'], string> = {
  published: 'bg-green-500/10 text-green-600 border-green-500/20',
  draft:     'bg-[var(--armada-accent)] text-[var(--armada-text)]/50 border-[var(--armada-accent)]',
  scheduled: 'bg-yellow-500/10 text-yellow-600 border-yellow-500/20',
};

const platformLabels: Record<Content['platform'], string> = {
  notion:       'Notion',
  google_drive: 'Google Drive',
  local:        'Stockage local', // i18n: Local Storage
};

export default function ContentPage() {
  const formatDate = (date: Date) =>
    date.toLocaleString('fr-FR', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });

  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--armada-bg)', color: 'var(--armada-text)' }}>

      {/* ── Header ── */}
      <div
        className="border-b border-[var(--armada-accent)]/50 px-6 py-5 flex items-center justify-between"
        style={{ backgroundColor: 'var(--armada-surface)' }}
      >
        <div>
          <h1 className="font-serif tracking-tight text-2xl text-[var(--armada-text)]">
            Bibliothèque de Contenu {/* i18n: Content Library */}
          </h1>
          <p className="text-[10px] font-mono text-[var(--armada-text)]/40 uppercase tracking-widest mt-0.5">
            Tout le contenu généré par vos agents {/* i18n: All content generated by your agents */}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            className="px-5 py-2 rounded-full border border-[var(--armada-accent)] text-[var(--armada-text)]/60 text-xs font-medium hover:bg-[var(--armada-surface-hover)] hover:text-[var(--armada-text)] transition-all"
          >
            Filtres {/* i18n: Filters */}
          </button>
          <button
            className="px-5 py-2 rounded-full text-white text-xs font-medium transition-all hover:opacity-90 armada-btn-primary"
            style={{ backgroundColor: 'var(--armada-primary)' }}
          >
            Demander du contenu {/* i18n: Request Content */}
          </button>
        </div>
      </div>

      {/* ── Stats bar ── */}
      <div
        className="border-b border-[var(--armada-accent)]/50 px-6 py-4 flex items-center gap-8"
        style={{ backgroundColor: 'var(--armada-surface)' }}
      >
        {[
          { value: contents.length, label: 'Total' },
          { value: contents.filter(c => c.status === 'published').length, label: 'Publiés' },     // i18n: Published
          { value: contents.filter(c => c.status === 'draft').length, label: 'Brouillons' },      // i18n: Drafts
          { value: contents.reduce((s, c) => s + c.wordCount, 0).toLocaleString('fr-FR'), label: 'Mots' }, // i18n: Words
        ].map(s => (
          <div key={s.label}>
            <div className="text-xl font-bold font-mono text-[var(--armada-text)] leading-none">{s.value}</div>
            <div className="text-[9px] font-mono text-[var(--armada-text)]/40 uppercase tracking-widest mt-1">{s.label}</div>
          </div>
        ))}
      </div>

      {/* ── Content list ── */}
      <div className="p-6">
        <div className="grid grid-cols-1 gap-3 max-w-5xl mx-auto">
          {contents.map((content) => (
            <div
              key={content.id}
              className="rounded-2xl border border-[var(--armada-accent)]/50 armada-card overflow-hidden hover:border-[var(--armada-primary)]/30 transition-all duration-300"
              style={{ backgroundColor: 'var(--armada-surface)' }}
            >
              <div className="p-5">
                <div className="flex items-start gap-5">
                  {/* Platform icon */}
                  <div
                    className="p-2.5 rounded-xl border border-[var(--armada-primary)]/20 flex-shrink-0"
                    style={{ backgroundColor: 'color-mix(in srgb, var(--armada-primary) 8%, transparent)' }}
                  >
                    <FileText className="h-4 w-4" style={{ color: 'var(--armada-primary)' }} />
                  </div>

                  {/* Body */}
                  <div className="flex-1 space-y-2.5 min-w-0">
                    {/* Title row */}
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <h3 className="font-serif text-base text-[var(--armada-text)] truncate">{content.title}</h3>
                        <p className="text-xs text-[var(--armada-text)]/50 mt-0.5 line-clamp-2">{content.preview}</p>
                      </div>
                      <div className="flex items-center gap-2 flex-shrink-0">
                        {content.link && (
                          <button
                            onClick={() => window.open(content.link, '_blank')}
                            className="flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-[var(--armada-accent)] text-[var(--armada-text)]/50 text-xs hover:text-[var(--armada-text)] hover:bg-[var(--armada-surface-hover)] transition-colors"
                          >
                            Ouvrir {/* i18n: Open */}
                            <ExternalLink className="h-3 w-3" />
                          </button>
                        )}
                        <button className="p-1.5 rounded-full border border-[var(--armada-accent)] text-[var(--armada-text)]/40 hover:text-[var(--armada-text)] hover:bg-[var(--armada-surface-hover)] transition-colors">
                          <Download className="h-3.5 w-3.5" />
                        </button>
                      </div>
                    </div>

                    {/* Meta row */}
                    <div className="flex items-center gap-2.5 flex-wrap">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full border text-[10px] font-mono ${typeColors[content.type]}`}>
                        {typeLabels[content.type]}
                      </span>
                      <span className="text-[10px] font-mono text-[var(--armada-text)]/40">
                        Agent : {content.agent}
                      </span>
                      <span className="text-[var(--armada-accent)]">·</span>
                      <span className="text-[10px] font-mono text-[var(--armada-text)]/40">
                        {content.wordCount.toLocaleString('fr-FR')} mots {/* i18n: words */}
                      </span>
                      <span className="text-[var(--armada-accent)]">·</span>
                      <span className="text-[10px] font-mono text-[var(--armada-text)]/40">
                        {formatDate(content.createdAt)}
                      </span>
                      <span className="text-[var(--armada-accent)]">·</span>
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full border text-[10px] font-mono ${statusColors[content.status]}`}>
                        {statusLabels[content.status]}
                      </span>
                    </div>

                    {/* Platform */}
                    <div className="pt-2 border-t border-[var(--armada-accent)]/40">
                      <span className="text-[9px] font-mono text-[var(--armada-text)]/30 uppercase tracking-widest">
                        Stocké dans : {/* i18n: Stored in: */}
                      </span>
                      <span className="text-[9px] font-mono ml-1" style={{ color: 'var(--armada-primary)' }}>
                        {platformLabels[content.platform]}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
